### ISSUE TITLE
CONDA_PREFIX patch fails when CONDA_PREFIX not set

### ISSUE THREAD

**Issue by eschellerup** [AnacondaRecipes/pycryptodome-feedstock#1]
https://github.com/AnacondaRecipes/pycryptodome-feedstock/blob/926fcd12d465c00fffa98007bc5ac0e2c4c6382b/recipe/0001-Make-load_lib-CONDA_PREFIX-aware.patch#L34

When running the patched pycryptodome outside of an activated Conda environment we get the following failure:
```
>>> import os
>>> os.environ['CONDA_PREFIX']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'CONDA_PREFIX'
```

**Comment by mingwandroid** [comment]
> When running the patched pycryptodome outside of an activated Conda environment

This is not supported, sorry. Please activate.
